name: wger-dev

services:
  web:
    build:
      dockerfile: server.dev.Dockerfile
    env_file:
      - ../config/prod.env
      - ../config/dev.env
      - ../config/dev-sqlite.env
    volumes:
      - type: bind
        source: ${WGER_CODEPATH:?set the absolute path to the wger backend code in the .env file or env variable}
        target: /home/wger/src
    ports:
      - "8000:8000"
    # We use something here that never ends. The server is started manually
    command: tail -f /dev/null

  cache:
    image: redis
    expose:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
