services:
  prometheus:
    image: prom/prometheus:latest
    restart: 'no'
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./web.yml:/etc/prometheus/web.yml
      - ./wger.rules:/etc/prometheus/wger.rules
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
    expose:
      - 9090

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    restart: 'no'
    volumes:
      - grafana_data:/var/lib/grafana
    expose:
      - 3000
    depends_on:
      - prometheus

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  default:
    name: wger_network
    external: true
