services:
  prometheus:
    image: prom/prometheus:latest
    restart: 'no'
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./web.yml:/etc/prometheus/web.yml
      - ./wger.rules:/etc/prometheus/wger.rules
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    restart: 'no'
    volumes:
      - grafana_data:/var/lib/grafana
    expose:
      - 3000

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  alloy:
    image: grafana/alloy:latest
    volumes:
      - docker_caddy-logs:/var/log/www
      - ./config.alloy:/etc/alloy/config.alloy
    ports:
      - "9080:9080"
    command:  --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

#  node_exporter:
#    image: prom/node-exporter:latest
#    command:
#      - '--path.rootfs=/host'
#    expose:
#      - 9100
#    restart: unless-stopped
#    volumes:
#      - '/:/host:ro,rslave'



volumes:
  prometheus_data:
  grafana_data:
  docker_caddy-logs:
    external: true

networks:
  default:
    name: wger_network
    external: true
